// Generates CLI reference pages from goke's generateDocs() into website/src/docs/cli/*.mdx.
// Run with: bun scripts/generate-cli-docs.ts
// Uses bun because the CLI source has TS parameter properties that Node strip-only mode rejects.

import fs from 'node:fs'
import path from 'node:path'
import { generateDocs } from 'goke'
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js'
import { addCliToolsToMcp } from '@goke/mcp'
import { cli, isMcpCommand } from 'strada/src/cli'

const outDir = path.resolve(import.meta.dirname, '../src/docs/cli')

const icons: Record<string, string> = {
  database: 'lucide:database',
  login: 'lucide:log-in',
  logout: 'lucide:log-out',
  whoami: 'lucide:user',
  setup: 'lucide:settings',
  orgs: 'lucide:building-2',
  projects: 'lucide:folder',
  issues: 'lucide:bug',
  analytics: 'lucide:bar-chart-3',
  query: 'lucide:search',
  alerts: 'lucide:bell',
  checks: 'lucide:heart-pulse',
  destinations: 'lucide:send',
  logs: 'lucide:scroll-text',
  services: 'lucide:server',
  traces: 'lucide:route',
  tokens: 'lucide:key',
  mcp: 'lucide:plug',
}

const pages = generateDocs({ cli, basePath: '.' })

if (fs.existsSync(outDir)) {
  fs.rmSync(outDir, { recursive: true })
}
fs.mkdirSync(outDir, { recursive: true })

console.log(`Generating ${pages.length} CLI doc pages into ${outDir}`)

for (const page of pages) {
  const title = page.command ? `strada ${page.command}` : 'Strada CLI command reference'
  const icon = icons[page.slug.split('-')[0]] || 'lucide:terminal'
  const sidebarTitle = page.command || 'Overview'
  const frontmatter = [
    '---',
    '# This file is auto-generated by scripts/generate-cli-docs.ts. Do not edit manually.',
    '$schema: https://holocron.so/frontmatter.json',
    `title: "${title}"`,
    `sidebarTitle: "${sidebarTitle}"`,
    `icon: ${icon}`,
    'prompt: |',
    '  Generate this CLI page from goke generateDocs() via',
    '  @/website/scripts/generate-cli-docs.ts and @/cli/src/.',
    '---',
    '',
  ].join('\n')

  const content = page.content.replace(/\]\(\.\/([^)]+)\.md\)/g, '](./$1.mdx)')
  const filePath = path.join(outDir, `${page.slug}.mdx`)
  fs.writeFileSync(filePath, frontmatter + content)
  console.log(`  wrote docs/cli/${page.slug}.mdx`)
}

console.log('Done!')

const server = new Server({ name: 'strada', version: '1.0.0' }, { capabilities: {} })
addCliToolsToMcp({ cli, server, commandFilter: isMcpCommand })

const client = new Client({ name: 'docs-generator', version: '1.0.0' })
const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair()
await server.connect(serverTransport)
await client.connect(clientTransport)
const { tools } = await client.listTools()
await client.close()
await server.close()

const mcpOutFile = path.resolve(import.meta.dirname, '../mcp-tools.json')
fs.writeFileSync(mcpOutFile, JSON.stringify({ tools }, null, 2) + '\n')
console.log(`wrote ${mcpOutFile} (${tools.length} tools)`)
