/** Subset of the full SDK attribute keys. Values must match `@strada.sh/sdk` ATTR. */
export const ATTR = {
  "service.name": "service.name",
  "service.version": "service.version",
  "deployment.environment.name": "deployment.environment.name",
  "deployment.id": "deployment.id",
  "vcs.ref.head.revision": "vcs.ref.head.revision",
  "vcs.ref.head.name": "vcs.ref.head.name",
  "event.name": "event.name",
  "user.id": "user.id",
  "user.email": "user.email",
  "user.name": "user.name",
  "user.full_name": "user.full_name",
  "user.hash": "user.hash",
  "user.image": "user.image",
  "organization.id": "organization.id",
  "organization.name": "organization.name",
  "strada.user.identify": "strada.user.identify",
  "exception.type": "exception.type",
  "exception.message": "exception.message",
  "exception.stacktrace": "exception.stacktrace",
  "exception.mechanism.type": "exception.mechanism.type",
  "exception.mechanism.handled": "exception.mechanism.handled",
  "exception.fingerprint": "exception.fingerprint",
  "session.id": "session.id",
  "url.path": "url.path",
  "url.query": "url.query",
  "url.full": "url.full",
  "http.request.header.referer": "http.request.header.referer",
  "pageview.source": "pageview.source",
} as const;
